services:
  pwnlab:
    build:
      context: .
      dockerfile: Dockerfile

    image: pwnlab:local

    hostname: pwnlab

    stdin_open: true
    tty: true

    # Persistent workspace
    volumes:
      - ./workspace:/workspace

    # Normal Docker networking = Internet access
    network_mode: bridge

    # Required for GDB/Pwndbg debugging
    cap_add:
      - SYS_PTRACE

    # Makes debugging unrestricted inside the container
    security_opt:
      - seccomp=unconfined

    environment:
      TERM: xterm-256color
      COLORTERM: truecolor

    working_dir: /workspace