services:
  pwnlab:
    build:
      context: .
      dockerfile: Dockerfile

    image: pwnlab:local

    hostname: pwnlab

    stdin_open: true
    tty: true

    volumes:
      - ./workspace:/workspace

    environment:
      TERM: xterm-256color
      COLORTERM: truecolor

    network_mode: bridge

    cap_add:
      - SYS_PTRACE

    security_opt:
      - seccomp=unconfined

    working_dir: /workspace

    entrypoint: ["/usr/local/bin/pwnlab-entrypoint"]