services:
  pwnlab:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pwnlab

    stdin_open: true
    tty: true

    init: true

    working_dir: /workspace

    volumes:
      - ${PWN_WORKSPACE}:/workspace

    environment:
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      TERM: xterm-256color
      COLORTERM: truecolor

    cap_add:
      - SYS_PTRACE

    security_opt:
      - seccomp=unconfined

    restart: "no"